#!/usr/bin/env python3
"""Convert a TTF subset into an embeddable LovyanGFX VLW (anti-aliased) font.

VLW is 8-bit-alpha per pixel, so small text renders smooth (blended over the
background) instead of the jagged 1-bit GFX fonts. Format (big-endian uint32),
matching LovyanGFX's VLWfont::loadFont:
  Header (24B): gCount, version(11), sizePt, 0, ascent, descent
  Per glyph (28B, sorted by unicode): unicode, height, width, xAdvance, dY, dX, 0
  Bitmaps: each glyph's width*height bytes of 8-bit coverage, concatenated.
Emit as `const uint8_t <var>[] = {...}` for lcd.loadFont(<var>).
"""
import sys
import struct
import freetype

def be(v):
    return struct.pack(">i", v) if v < 0 else struct.pack(">I", v & 0xFFFFFFFF)

def convert(ttf_path, out_path, var_name, size_pt=11, first=0x20, last=0x7E, dpi=141):
    face = freetype.Face(ttf_path)
    face.set_char_size(size_pt * 64, 0, dpi, dpi)
    ascent  = face.size.ascender >> 6
    descent = abs(face.size.descender >> 6)

    glyphs = []  # (unicode, w, h, xAdvance, dY, dX, bitmap bytes)
    for code in range(first, last + 1):
        face.load_char(chr(code), freetype.FT_LOAD_RENDER)   # 8-bit anti-aliased
        g = face.glyph
        b = g.bitmap
        w, h, pitch, buf = b.width, b.rows, b.pitch, b.buffer
        data = bytearray(w * h)
        for y in range(h):
            for x in range(w):
                data[y * w + x] = buf[y * pitch + x]
        glyphs.append((code, w, h, g.advance.x >> 6, g.bitmap_top, g.bitmap_left, bytes(data)))
    glyphs.sort(key=lambda gl: gl[0])

    blob = bytearray()
    blob += be(len(glyphs)) + be(11) + be(size_pt) + be(0) + be(ascent) + be(descent)
    for (u, w, h, xa, dY, dX, _d) in glyphs:
        blob += be(u) + be(h) + be(w) + be(xa) + be(dY) + be(dX) + be(0)
    for (u, w, h, xa, dY, dX, d) in glyphs:
        blob += d

    lines = []
    lines.append("// Auto-generated by tools/ttf_to_vlw.py — do not edit by hand.")
    lines.append("// Source: %s  size=%dpt dpi=%d  range=0x%02X..0x%02X (anti-aliased VLW)" %
                 (ttf_path.split("\\")[-1], size_pt, dpi, first, last))
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("static const uint8_t %s[] = {" % var_name)
    row = "  "
    for bcount, byte in enumerate(blob):
        row += "0x%02X," % byte
        if len(row) >= 110:
            lines.append(row); row = "  "
    if row.strip():
        lines.append(row)
    lines.append("};")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s  (%d glyphs, %d bytes, ascent=%d descent=%d)" %
          (out_path, len(glyphs), len(blob), ascent, descent))

if __name__ == "__main__":
    kw = {}
    if len(sys.argv) > 4:
        kw["size_pt"] = int(sys.argv[4])
    if len(sys.argv) > 6:
        kw["first"] = int(sys.argv[5], 0)
        kw["last"] = int(sys.argv[6], 0)
    convert(sys.argv[1], sys.argv[2], sys.argv[3], **kw)
