#!/usr/bin/env python3
"""Convert a TTF subset into a LovyanGFX lgfx::GFXfont header.

Mirrors Adafruit fontconvert (DPI 141, MSB-first, per-glyph byte alignment) but
emits the lgfx::GFXfont / lgfx::GFXglyph types LovyanGFX uses. Only the glyph
range we need is embedded (the big % number renders digits and '%').
"""
import sys
import freetype

def remove_orphans(grid, w, h):
    """Clear set pixels that have no orthogonal (4-neighbour) set neighbour.
    Removes lone rasterization spurs (e.g. the 1px tail on '%') without touching
    real strokes, which are >=2px wide and so always have a neighbour."""
    out = [row[:] for row in grid]
    for y in range(h):
        for x in range(w):
            if not grid[y][x]:
                continue
            n = 0
            if x > 0 and grid[y][x - 1]:     n += 1
            if x < w - 1 and grid[y][x + 1]: n += 1
            if y > 0 and grid[y - 1][x]:     n += 1
            if y < h - 1 and grid[y + 1][x]: n += 1
            if n == 0:
                out[y][x] = 0
    return out

def convert(ttf_path, out_path, var_name, size_pt=18, first=0x25, last=0x39, dpi=141,
            despur=True):
    face = freetype.Face(ttf_path)
    # width in 1/64 pt, hres/vres = dpi  (matches Adafruit fontconvert)
    face.set_char_size(size_pt * 64, 0, dpi, dpi)

    bitmaps = bytearray()
    glyphs = []   # (offset, w, h, xAdvance, xOffset, yOffset, ch)
    for code in range(first, last + 1):
        face.load_char(chr(code), freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
        g = face.glyph
        bmp = g.bitmap
        w, h, pitch, buf = bmp.width, bmp.rows, bmp.pitch, bmp.buffer
        # Build the glyph grid, optionally despur, then pack.
        grid = [[(buf[y * pitch + (x >> 3)] >> (7 - (x & 7))) & 1 for x in range(w)]
                for y in range(h)]
        if despur:
            grid = remove_orphans(grid, w, h)

        offset = len(bitmaps)
        # Pack w*h bits MSB-first; pad the final byte (per-glyph byte alignment).
        acc, nbits = 0, 0
        for y in range(h):
            for x in range(w):
                acc = (acc << 1) | grid[y][x]
                nbits += 1
                if nbits == 8:
                    bitmaps.append(acc)
                    acc, nbits = 0, 0
        if nbits:
            bitmaps.append(acc << (8 - nbits))

        glyphs.append((offset, w, h, g.advance.x >> 6, g.bitmap_left, -g.bitmap_top, code))

    y_advance = face.size.height >> 6

    lines = []
    lines.append("// Auto-generated by tools/ttf_to_lgfx_gfxfont.py — do not edit by hand.")
    lines.append("// Source: %s  size=%dpt dpi=%d  range=0x%02X..0x%02X" %
                 (ttf_path.split("\\")[-1], size_pt, dpi, first, last))
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("static const uint8_t %sBitmaps[] = {" % var_name)
    row = "  "
    for i, b in enumerate(bitmaps):
        row += "0x%02X," % b
        if len(row) >= 96:
            lines.append(row); row = "  "
    if row.strip():
        lines.append(row)
    lines.append("};")
    lines.append("")
    lines.append("static const lgfx::GFXglyph %sGlyphs[] = {" % var_name)
    for off, w, h, xa, xo, yo, code in glyphs:
        ch = chr(code) if code != 0x5C else "backslash"
        lines.append("  { %5d, %3d, %3d, %3d, %4d, %4d }, // '%s' 0x%02X" %
                     (off, w, h, xa, xo, yo, ch, code))
    lines.append("};")
    lines.append("")
    lines.append("static const lgfx::GFXfont %s(" % var_name)
    lines.append("  (uint8_t*)%sBitmaps, (lgfx::GFXglyph*)%sGlyphs, 0x%02X, 0x%02X, %d);" %
                 (var_name, var_name, first, last, y_advance))
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s  (%d glyphs, %d bitmap bytes, yAdvance=%d)" %
          (out_path, len(glyphs), len(bitmaps), y_advance))

if __name__ == "__main__":
    convert(sys.argv[1], sys.argv[2], sys.argv[3],
            size_pt=int(sys.argv[4]) if len(sys.argv) > 4 else 18)
